wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.36.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702824005.405816
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 50
      - 51
      - 53
      - 55
      - 64
      - 71
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 50
      - 51
      - 53
      - 55
      - 64
      - 71
      3:
      - 23
      4: 3.10.0
      5: 0.16.1
      6: 4.36.1
      8:
      - 5
      13: linux-x86_64
